# API documentation configuration file
# Used for https://vipps.no/developer-pages
# This file will be fetched by the user's browser
# Do not store personal or confidental information in this file

# Short name of the API
apiShortName: Get started

# This will appear as the title on the API page
apiLongName: Get started

# Short introduction to the API
introduction: Resources for getting started with Vipps services

# The name of the group in Vipps that is responsible for maintaining the code
# This does not appar on the page
owner: VippsAS

# GitHub url of the repository
githubRepo: https://github.com/vippsas/vipps-developers

# List of markdown files
# - title: Short name of the document to be displayed. (eg. Getting started)
# - slug: Used to identify the document, must be unique. (eg. getting-started)
# - description: Short text of what useful information is contained in the document. (eg. Start here if you plan to integrate with our API)
# - markdownUrl: Url to the markdown source file (eg. vipps-ecom-api/devpages-restructure/vipps-ecom-api.md)
# - githubUrl: (optional) Url to GitHub, where the user can make issues and PRs
resources:
  - title: Get Started
    slug: get-started
    description: Get started guide for Vipps APIs
    markdownUrl: vipps-developers/vipps-getting-started.md
    githubUrl: https://github.com/vippsas/vipps-developers/blob/master/vipps-getting-started.md
  - title: Postman Guide
    slug: postman-guide
    description: A guide for using Postman with Vipps APIs
    markdownUrl: vipps-developers/postman-guide.md
    githubUrl: https://github.com/vippsas/vipps-developers/blob/master/postman-guide.md
  - title: Test Environment
    slug: test-environment
    description: An overview of Vipps test environment and test apps
    markdownUrl: vipps-developers/vipps-test-environment.md
    githubUrl: https://github.com/vippsas/vipps-developers/blob/master/vipps-test-environment.md
  - title: Design Guidelines
    slug: design-guidelines
    description: These guidelines will help you use the Vipps payments
    markdownUrl: vipps-design-guidelines/master/README.md
    githubUrl: https://github.com/vippsas/vipps-design-guidelines/blob/master/README.md
  - title: GitHub resources
    slug: github-resources
    description: All developer resources on GitHub
    markdownUrl: vipps-developers/master/README.md
    githubUrl: https://github.com/vippsas/
  - title: Contact Us
    slug: contact
    description: Contact information for Vipps Integration
    markdownUrl: vipps-developers/devpages-restructure/contact.md
    githubUrl: https://github.com/vippsas/vipps-developers/blob/devpages-restructure/contact.md

# External links to developer resources at the top of the documentation page
# Optional
linklist:
  - title: Vipps customer portal
    url: https://portal.vipps.no
