# API documentation configuration file
# Used for https://vipps.no/developer-pages
# This file will be fetched by the user's browser
# Do not store personal or confidental information in this file

# Short name of the API
apiShortName: Invoice

# This will appear as the title on the API page
apiLongName: Vipps Invoice API

# Short introduction to the API
introduction: Invoice API for ISP and IPP

# The name of the group in Vipps that is responsible for maintaining the code
# This does not appar on the page
owner: VippsAS

# GitHub url of the repository
githubRepo: https://github.com/vippsas/vipps-invoice-api

# List of markdown files
# - title: Short name of the document to be displayed. (eg. Getting started)
# - slug: Used to identify the document, must be unique. (eg. getting-started)
# - description: Short text of what useful information is contained in the document. (eg. Start here if you plan to integrate with our API)
# - markdownUrl: Url to the markdown source file (eg. vipps-ecom-api/master/vipps-ecom-api.md)
# - githubUrl: (optional) Url to GitHub, where the user can make issues and PRs
resources:
  - title: Introduction
    slug: introduction
    description: Information about test environment, terminology and valid banks
    markdownUrl: vipps-invoice-api/master/README.md
    githubUrl: https://github.com/vippsas/vipps-invoice-api/blob/master/README.md
  - title: Documentation
    slug: documentation
    description: Read the documentation of our invoice API
    markdownUrl: vipps-invoice-api/master/vipps-invoice-api.md
    githubUrl: https://github.com/vippsas/vipps-invoice-api/blob/master/vipps-invoice-api.md
  - title: Checklist
    slug: checklist
    description: Checklist for integrations
    markdownUrl: vipps-invoice-api/master/vipps-integrator-checklist.md
    githubUrl: https://github.com/vippsas/vipps-invoice-api/blob/master/vipps-integrator-checklist.md

# External links to developer resources at the top of the documentation page
# Optional
linklist:
  - title: Getting Started
    url: https://github.com/vippsas/vipps-developers/blob/master/vipps-getting-started.md
  - title: Postman Collection & Environment
    url: https://github.com/vippsas/vipps-invoice-api/tree/master/tools
  - title: Swagger
    url: https://vippsas.github.io/vipps-invoice-api/
  - title: Vipps customer portal
    url: https://portal.vipps.no
